### ISSUE TITLE
Consider to add Balinese fonts

### ISSUE THREAD

**Issue by mahalisyarifuddin** [r12a/shared#1]
It would be great if [these fonts by Panlex](https://github.com/longnow/bali-fonts) is added to the Balinese picker, because the existing fonts (Aksara Bali and Noto) is actually not that great.

Thank you.

**Comment by r12a** [comment]
Thanks for the prompt, @mahalisyarifuddin   You caught me at a good time, so i have already updated the font pulldown list.

I'll experiment a little with the font and if all goes well i'll replace the webfont with this, given that the licence seems to allow it.
